### ISSUE TITLE
Crash when launching new campaign

### ISSUE THREAD

**Issue by sleepadru** [admiralnelson/EnableAchievement#1]
Crashes during Hero Creation screen, after selecting "New Campaign"
Game version 1.2.0

https://gist.github.com/sleepadru/b4183c7a93c5b44c212e534d801a01dd

**Comment by salamieri** [comment]
Thanks for your work, just wanted to post here :)

**Comment by salamieri** [comment]
Closing due to mod mismatch; Lots of mods apparently don't work :)
